### ISSUE TITLE
홈페이지의 주제가 중요한가? 기능 구현이 중요한가?

### ISSUE THREAD

**Issue by wmfgngn** [wmfgngn/TeamProject#1]
의견 말해주세요

ex) 쇼핑몰 홈페이지를 만들자 or mvc 잘 쓰기만하면 된다

**Comment by o2o25252** [comment]
우리 프사 바까요

**Comment by hd10050** [comment]
데이터베이스 설계는 저희가 나중에 따로합니다.
우선 html + css 구현후 백앤드작업을 합니다.

**Comment by wmfgngn** [comment]
그럼 이미지나 텍스트는 일단 임의로 두고 할겠습니다

**Comment by Isoop** [comment]
sk로 할거면 view는 상세 이미지 없는데 야매로 만드나여?

**Comment by hd10050** [comment]
쇼핑몰 나쁘지 않은것 같습니다

**Comment by wmfgngn** [comment]
주제 우선 결정으로 종결
