### ISSUE TITLE
데이터베이스 DDL

### ISSUE THREAD

**Issue by hd10050** [wmfgngn/TeamProject#4]
--------------------------------------------------------
-- INVEN_BBS 테이블 생성
--------------------------------------------------------

CREATE TABLE INVEN_BBS
(
B_IDX NUMBER(6, 0) NOT NULL
, SUBJECT VARCHAR2(50 BYTE)
, WRITER VARCHAR2(20 BYTE)
, CONTENT CLOB
, FILE_NAME VARCHAR2(50 BYTE)
, ORI_NAME VARCHAR2(50 BYTE)
, PWD VARCHAR2(20 BYTE)
, WRITE_DATE DATE
, IP VARCHAR2(30 BYTE)
, HIT NUMBER(4, 0)
, STATUS NUMBER(1, 0)
, KATEGORIE VARCHAR2(20 BYTE)
, RECOMMEND VARCHAR2(20 BYTE)
, TYPE NUMBER);

--------------------------------------------------------
-- INVEN_BBS 테이블의 기본키설정
--------------------------------------------------------

  ALTER TABLE "HR"."INVEN_BBS" ADD CONSTRAINT "B_IDX" PRIMARY KEY ("B_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;

--------------------------------------------------------
--  INVEN_COMMENT 테이블 생성
--------------------------------------------------------

  CREATE TABLE "HR"."INVEN_COMMENT" 
   (	"C_IDX" NUMBER(6,0), 
	"WRITER" VARCHAR2(20 BYTE), 
	"CONTENT" CLOB, 
	"PWD" VARCHAR2(20 BYTE), 
	"WRITE_DATE" DATE, 
	"IP" VARCHAR2(30 BYTE), 
	"B_IDX" NUMBER(6,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
--------------------------------------------------------
--  INVEN_COMMENT 기본키, 외래키 설정
--------------------------------------------------------
  ALTER TABLE "HR"."INVEN_COMMENT" ADD CONSTRAINT "COMM_FK" FOREIGN KEY ("B_IDX")
	  REFERENCES "INVEN_BBS" ("B_IDX") ENABLE;

ALTER TABLE "HR"."INVEN_COMMENT" ADD CONSTRAINT "COMMENT_PK" PRIMARY KEY ("C_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;

**Comment by wmfgngn** [comment]
미쳤다
ㅋㅋㅋ
