### ISSUE TITLE
회원 가입 SQL 이거좀 봐줘 

### ISSUE THREAD

**Issue by o2o25252** [wmfgngn/TeamProject#5]
CREATE TABLE Regist_t (
    s_id VARCHAR2(50) not null CONSTRAINT Regist_t_pk PRIMARY KEY,
    s_pw VARCHAR2(50) not null,
    s_name VARCHAR2(100),
    s_phone VARCHAR2(200),
    s_gender NUMBER(1),
    status NUMBER(1)   
);
status 0 , 1 로 탈퇴 확인 젠더 0 , 1로 남여 판단
**------------------------------------------------------------------------------------**
CREATE SEQUENCE Regist_t_seq
	increment by 1
	start with 1
	nomaxValue;
시퀀스 넘버
---------------------------------------------------------------------------------------

**Comment by wmfgngn** [comment]
이거 만들어도 되냐
