### ISSUE TITLE
regist_t 테이블 column 추가

### ISSUE THREAD

**Issue by hd10050** [wmfgngn/TeamProject#8]
ALTER TABLE REGIST_T
ADD (b_idx NUMBER(6,0));

ALTER TABLE regist_t
ADD CONSTRAINT regist_t_fk
FOREIGN KEY (b_idx)
REFERENCES inven_bbs (b_idx);

--------------------------------------------------------------------------------
BbsVO에 RegVO정보를 저장해야해서 테이블 컬럼을 추가했습ㄴ디ㅏ
inven_bbs의 b_idx를 참조하는 외래키를 추가하는 SQL문입니다.

**Comment by o2o25252** [comment]
확실한 D 체계 죠습니다 죠스는 한글로 상어입니다.
